#!/usr/bin/python
from helpers import *


import sys


if len(sys.argv) < 3 or len(sys.argv) > 4 :
      print " Usage :  ./main.py -[index/query]  [ (document/directory) / 'query_string' ]"
else:
      if sys.argv[1] == "-index":
            index = index(sys.argv[2])
            print_statistics(index,'the')
      elif sys.argv[1] == "-query":
            result = run_query(sys.argv[2])
            ##for x in result:
            ##	print x
      else:
            print " Usage :  ./main.py -[index/query]  [ (document/directory) / 'query_string' ]"